apiVersion: v1
kind: Pod
metadata: 
  name: mysql-pod
  namespace: default
spec:
  containers:
  - name: fakemysql-container
    image: busybox
    command:
    - sleep
    - "3600"
    env: 
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysql
          key: password
