apiVersion: v1
kind: Pod
metadata:
  name: secretbox-pod
  namespace: default
spec:
  containers:
  - name: secretbox-container
    image: busybox
    command:
      - sleep
      - "3600"
    volumeMounts:
    - mountPath: /secretstuff
      name: secret-volume
  volumes:
  - name: secret-volume
    secret:
      secretName: secretstuff
