apiVersion: v1
kind: Pod
metadata:
  name: nginx-toleration-pod
  labels: 
    env: test
spec:
  containers:
  - name: nginx-toleration-container
    image: nginx
    imagePullPolicy: IfNotPresent
  tolerations:
  - key: "example-key"
    operator: "Exists"
    effect: "NoSchedule"
