apiVersion: v1
kind: Service
metadata:
  name: lab7nginx
spec:
  selector:
    app: lab7nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9376
---
apiVersion: v1
kind: Service
metadata:
  name: lab7mysql
spec:
  selector:
    app: lab7mysql
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9377 
