apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lab6-pvc
  labels:
    task: lab6
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Mi
