apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: demodeployment
  name: demodeployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demodeployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: demodeployment
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
